name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
permissions:
  id-token: write
  pull-requests: write
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        run: sed -En 's/^go[[:space:]]+([[:digit:].]+)$/GO_VERSION=\1/p' go.mod >> $GITHUB_ENV
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - run: make toolchain verify
      - 
        run: echo ${{ secrets.MY_GITHUB_TOKEN }} | docker login ghcr.io -u bwagner5 --password-stdin
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - run: |
          make update-readme
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          git config user.name "Release"
          git config user.email "release@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}
          git config pull.rebase false

          BRANCH_NAME="release-${RELEASE_VERSION}"
          git checkout -b "${BRANCH_NAME}"
          git add README.md
          git commit -m "Release updates ${RELEASE_VERSION}."
          git push --set-upstream origin "${BRANCH_NAME}"
          gh pr create --title "chore: Release ${RELEASE_VERSION}" --body "Release ${RELEASE_VERSION}" --base main --head "release-${RELEASE_VERSION}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}